name: CI Action

on: 
  push:
    branches-ignore:
      - 'main'
      - 'gh-pages'
  pull_request:
    branches-ignore:
      - 'main'
      - 'gh-pages'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run lint:css
    - run: npm run lint:js
    - run: npm run build
    - run: npm run validate
  

